@startuml ApplicationConfiguration
!include ../../../../../../style/class.pu

class configuration.ApplicationConfiguration {
  - version : String {frozen}

  --

  + ApplicationConfiguration(version : String)
  + currentServerVersion(): Mono<String>
}

@enduml
