@startuml "aggiunta-gestore"
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as A

rectangle {
  together {
    usecase (AUC12.1) as "AUC12.1\nInserimento email gestore"
  }
}

:A: -- AUC12.1

@enduml
