@startuml aggiunta-visualizzatore
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as A

rectangle {
  together {
    usecase (AUC9.1) as "AUC9.1\nInserimento email visualizzatore"
  }
}

:A: -- AUC9.1

@enduml
