@startuml creazione-owner
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (AUC11) as "AUC11.1\nConferma aumento privilegi ad owner"
  }
}

:A: -- AUC11

@enduml
