@startuml creazione-owner
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (AUC7) as "AUC7.1\nConferma aumento privilegi ad owner"
  }
}

:A: -- AUC7

@enduml
