@startuml eliminazione-gestore
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as A2


rectangle {
  together {
    usecase (AUC15.1) as "AUC15.1\nInserimento email gestore"
  }
}

:A2: -- AUC15.1

@enduml
