@startuml eliminazione-visualizzatore
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as A2

rectangle {
    together {
        usecase (AUC16.1) as "AUC16.1\nInserimento email visualizzatore"
      }
  }

:A2: -- AUC16.1

@enduml
