@startuml eliminazione-account-wa
!include ../../../../../../commons/style/use-cases.pu

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC13.1) as "AUC13.1\nSeleziona account"
  }
}

:A: -- AUC13.1

@enduml
