
@startuml eliminazione-account-wa-conferma
!include ../../../../../../commons/style/use-cases.pu

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC17.1) as "AUC17.1\nConferma eliminazione account"
  }
}

:A: -- AUC17.1

@enduml
