@startuml eliminazione-owner
!include ../../../../../../commons/style/use-cases.pu

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC14.1) as "AUC14.1\nInserimento email owner"
  }
}

:A: -- AUC14.1

@enduml
