@startuml eliminazione-owner
!include ../../../../../../commons/style/use-cases.pu

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC10.1) as "AUC10.1\nInserimento email owner"
  }
}

:A: -- AUC10.1

@enduml
