@startuml gestione-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as O
actor :gestore: as G

rectangle {
    together {
        usecase (AUC3) as "AUC3\nCreazione organizzazione"
        usecase (AUC4) as "AUC4\nEliminazione organizzazione"
        usecase (AUC5) as "AUC5\nModifica organizzazione"
      }
  }

:G: -- AUC3.3
:G: -- AUC4
:O: -- AUC3

@enduml


@startuml creazione-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as O
actor :server LDAP: as S

rectangle {
    together {
        usecase (AUC3.1) as "AUC3.1\nInserisci nome organizzazione"
        usecase (AUC3.2) as "AUC3.2\nInserisci descrizione organizzazione"
        usecase (AUC3.3) as "AUC3.3\nConfigurazione IP server LDAP"
      }
  }

:O: -- AUC3.1
:O: -- AUC3.2
:O: -- AUC3.3

AUC3.3 -- :S:
@enduml


@startuml eliminazione-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as 0

rectangle {
    together {
        usecase (AUC4.1) as "AUC4.1\nConferma eliminazione organizzazione"
      }
  }

:0: -- AUC4.1
@enduml

@startuml modifica-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as O
actor :server LDAP: as S

rectangle {
    together {
        usecase (AUC5.1) as "AUC5.1\nModifica nome organizzazione"
        usecase (AUC5.2) as "AUC5.2\nModifica descrizione organizzazione"
        usecase (AUC5.3) as "AUC5.3\nModifica indirizzo IP server LDAP"
      }
  }

:O: -- AUC5.1
:O: -- AUC5.2
:O: -- AUC5.3

AUC5.3 -- :S:
@enduml
