@startuml gestione-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :gestore: as G
actor :owner: as O

rectangle {
    together {
        usecase (AUC3.4) as "AUC3.4\nSeleziona organizzazione"
        usecase (AUC3.3) as "AUC3.3\nModifica organizzazione"
        usecase (AUC3.2) as "AUC3.2\nEliminazione organizzazione"
        usecase (AUC3.1) as "AUC3.1\nCreazione organizzazione"
      }
  }

:O: -- AUC3.1
:G: -- AUC3.4

(AUC3.2) .up.> (AUC3.4) : <<extends>>
(AUC3.3) .up.> (AUC3.4) : <<extends>>

@enduml


@startuml creazione-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as O
actor :server LDAP: as S

rectangle {
    together {
        usecase (AUC3.1.1) as "AUC3.1.1\nInserisci nome organizzazione"
        usecase (AUC3.1.2) as "AUC3.1.2\nInserisci descrizione organizzazione"
        usecase (AUC3.1.3) as "AUC3.1.3\nConfigurazione dettagli server LDAP"
      }
  }

:O: -- AUC3.1.1
:O: -- AUC3.1.2
:O: -- AUC3.1.3

AUC3.1.3 -- :S:
@enduml


@startuml eliminazione-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :owner: as O

rectangle {
    together {
        usecase (AUC3.2.1) as "AUC3.2.1\nConferma eliminazione organizzazione"
      }
  }

:O: -- AUC3.2.1
@enduml

@startuml modifica-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :gestore: as G
actor :owner: as O
actor :server LDAP: as S

rectangle {
    together {
        usecase (AUC3.3.1) as "AUC3.3.1\nModifica nome organizzazione"
        usecase (AUC3.3.2) as "AUC3.3.2\nModifica descrizione organizzazione"
        usecase (AUC3.3.3) as "AUC3.3.3\nModifica configurazione dettagli server LDAP"
        usecase (AUC4) as "AUC4\nGestione luoghi"
      }
  }

:O: -- AUC3.3.1
:O: -- AUC3.3.2
:G: -- AUC4
:O: -- AUC3.3.3

AUC3.3.3 -- :S:
@enduml
