@startuml gestione-luoghi
!include ../../../../../../commons/style/use-cases.pu

actor :gestore: as G

rectangle {
  together {
    usecase (AUC6) as "AUC6\nAggiungi luogo"
    usecase (AUC8) as "AUC8\nEliminazione luogo"
    usecase (AUC7) as "AUC7\nModifica luogo"
  }
}

:G: -- AUC6
:G: -- AUC8
:G: -- AUC7

@enduml

@startuml aggiungi-luogo
!include ../../../../../../commons/style/use-cases.pu

actor :gestore: as G

rectangle {
  together {
    usecase (AUC6.1) as "AUC6.1\nInserisci coordinate geografiche"
    usecase (AUC6.2) as "AUC6.2\nInserisci indirizzo luogo"
  }
}

:G: -- AUC6.1
:G: -- AUC6.2

@enduml

@startuml modifica-luogo
!include ../../../../../../commons/style/use-cases.pu

actor :gestore: as G

rectangle {
  together {
    usecase (AUC7.1) as "AUC7.1\nModifica coordinate geografiche"
    usecase (AUC7.2) as "AUC7.2\nModifica indirizzo luogo"
  }
}

:G: -- AUC7.1
:G: -- AUC7.2

@enduml
