@startuml query-sul-dipendente
!include ../../../../../../commons/style/use-cases.pu

actor :visualizzatore: as A

rectangle {
  together {
    usecase (AUC6.1) as "AUC6.1\nVisualizza organizzazione dipendente"
    usecase (AUC6.2) as "AUC6.2\nVisualizza luogo dipendente"
  }
}

:A: -- AUC6.1
:A: -- AUC6.2

@enduml
