@startuml query-sul-dipendente
!include ../../../../../../commons/style/use-cases.pu

actor :visualizzatore: as A

rectangle {
  together {
    usecase (AUC10.1) as "AUC10.1\nVisualizza organizzazione dipendente"
    usecase (AUC10.2) as "AUC10.2\nVisualizza luogo dipendente"
  }
}

:A: -- AUC10.1
:A: -- AUC10.2

@enduml
