@startuml monitora-numero-dipendenti
!include ../../../../../../commons/style/use-cases.pu

actor :visualizzatore: as A

rectangle {
  together {
    usecase (AUC9.1) as "AUC9.1\n Monitora il numero di \ndipendenti in tutta l'organizzazione"
    usecase (AUC9.2) as "AUC9.2\nMonitora il numero di \ndipendenti in un luogo"
    usecase (AUC9.3) as "AUC9.3\nVisualizza report"
  }
}

:A: -- AUC9.1
:A: -- AUC9.2
:A: -- AUC9.3

@enduml
