@startuml LdapConfiguration diagram
!include ../../../style/class.pu
class LdapConfiguration <<interface>> {
  + host : String {readonly}
  + username : String {readonly}
  + password : String {readonly}
}
@enduml
