@startuml
!include ../../../../../commons/style/use-cases.pu

title UUC12 - Disconnessione utente

actor :utente autenticato: as A3

rectangle {
  together {
    usecase (UUC12) as "UUC12\nDisconnessione utente\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC5) as "UUC5\nVisualizzazione errore\nrete mancante"
  }
}

:A3: -- (UUC12)

(UUC5) .|> (UUC12) : <<extends>>

@enduml
