@startuml
!include ../../../../../commons/style/use-cases.pu

title UUC10 - Storico utente

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC10) as "UUC10\nVisualizzazione storico accessi\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta storico\nin mancanza di rete"
    usecase (UUC5) as "UUC5\nVisualizzazione errore\nrete mancante"
    note right of (UUC10): implementazione opzionale
  }
}

:A: -- (UUC10)

(UUC5) .up.|> (UUC10) : <<extends>>

@enduml
