@startuml
!include ../../../../../commons/style/use-cases.pu

title UUC11 - Visualizzazione tempo nell'organizzazione corrente

actor :utente autenticato: as A3
actor :utente collegato: as A3.1

:A3.1: -up-|> :A3:

rectangle {
  together {
    usecase (UUC11) as "UUC11\nVisualizzazione tempo \nnell'organizzazione corrente\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta tempo trascorso\nin mancanza di rete"
    usecase (UUC5) as "UUC5\nVisualizzazione errore\nrete mancante"
    note right of (UUC11): implementazione opzionale
  }
}

:A3.1: -- (UUC11)

(UUC5) .up.|> (UUC11) : <<extends>>

@enduml
