@startuml
!include ../../../../../commons/style/use-cases.pu

title UUC3 - Recupero credenziali

actor :utente non autenticato: as A

rectangle {
  together {
    usecase (UUC3.1) as "UUC3.1\nRecupero password" 
  }
}

:A: -- (UUC3.1)

@enduml
