@startuml
!include ../../../../../commons/style/use-cases.pu

title UUC4 - Recupero lista organizzazioni

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC4.1) as "UUC4.1\nVisualizzazione\nlista organizzazioni\n--\nExtension points:\nVisualizzazione errore causa\n-richiesta di visualizzazione della lista con rete mancante\n-aggiornamento della lista con rete mancante"
    usecase (UUC4.1.1) as "UUC4.1.1\nAggiornamento\nlista organizzazioni"
    usecase (UUC5) as "UUC5\nVisualizzazione errore\nrete mancante"
  }
}

:A: -- (UUC4.1)

(UUC4.1.1) .up.|> (UUC4.1) : <<include>>
(UUC5) .up.|> (UUC4.1) : <<extends>>

@enduml
