@startuml
!include ../../../../../commons/style/use-cases.pu

title UUC6 - Collegamento organizzazione

actor :utente autenticato: as A3
actor :utente non collegato: as A3.1

:A3.1: -up-|> :A3:

rectangle {
  together {
    usecase (UUC6.1) as "UUC6.1\nSelezionamento di un'organizzazione\n--\nExtension points:\nVisualizzazione errore in caso di\nselezionamento di un'organizzazione\n con rete mancante"
    usecase (UUC5) as "UUC5\nVisualizzazione errore\nrete mancante"
  }
}

:A3.1: -- (UUC6.1)

(UUC5) .|> (UUC6.1) : <<extends>>

@enduml
