@startuml
!include ../../../../../commons/style/use-cases.pu

title UUC8 - Scollegamento da organizzazioni multiple

actor :utente autenticato: as A3
actor :utente collegato: as A3.1
:A3.1: -up-|> :A3:

rectangle {
  together {
    usecase (UUC8) as "UUC8\nScollegamento da organizzazioni multiple\n--\nExtension points:\nVisualizzazione errore in caso di\nscollegamento dall'organizzazione\n con rete mancante"
    usecase (UUC5) as "UUC5\nVisualizzazione errore\nrete mancante"
  }
}

:A3.1: -- (UUC8)

(UUC5) .|> (UUC8) : <<extends>>

@enduml
