@startuml LdapConfiguration
!include ../../../../../../../style/class.pu

class model.api.LdapConfiguration {
  - host : String
  - username : String
  - password : String

  --

  + LdapConfiguration()
}
@enduml
