@startuml Decorator pattern diagram


title Decorator pattern diagram

!include ../../style/class.pu

!include ../classes/AuthenticatedRequest.pu

class com.android.volley.toolbox.JsonObjectRequest

AuthenticatedRequest -up-|> com.android.volley.toolbox.JsonObjectRequest
@enduml
