@startuml MVVM pattern diagram

title MVVM pattern diagram

!include ../../style/class.pu

!include ../classes/view/LoginActivity.pu
!include ../classes/viewmodel/LoginViewModel.pu
!include ../classes/model/LoginModel.pu

LoginActivity *-- LoginViewModel
LoginViewModel *-- LoginModel
@enduml
