@startuml OrganizationRole
!include ../../../../../../../style/class.pu

class model.db.OrganizationRole {
  - organizationId : Integer
  - userId : Integer
  - adminType : Integer
  - createdDate : DateTime

  --

  + OrganizationRole()
}

@enduml
