@startuml GetUserIdOrganizationsConnectionsResponse
!include ../../../../../../../../style/class.pu

' class model.api.responses.GetUserIdOrganizationsConnectionsResponse {
'   - id : Integer[]

'   --

'   + GetUserIdOrganizationsConnectionsResponse()
' }

@enduml
