@startuml OrganizationBuilder Diagram
!include ../../../style/class.pu
class AbsOrganizationBuilder {
  --

  + addPlaces(places : Place[])
  + build()
}

class OrganizationBuilder {
  - id : Integer
  - description : String
  - ldapConfiguration : LdapConfiguration
  - places : Place[]
  - createdDate : String
  - lastModifiedDate : String
  - name : String
  - isPrivate : Boolean

  --

  + OrganizationBuilder(private name : String, private isPrivate : Boolean)
  + addId(id : Integer) : OrganizationBuilder
  + addName(name : String) : OrganizationBuilder
  + addDescription(description : String) : OrganizationBuilder
  + addLdapConfiguration(
    ldapConfiguration : LdapConfiguration
    ) : OrganizationBuilder
  + addPlaces(places : Place[]) : OrganizationBuilder
  + addIsPrivate(isPrivate : Boolean) : OrganizationBuilder
  + addCreatedDate(createdDate : String) : OrganizationBuilder
  + addLastModifiedDate(
    lastModifiedDate : String
    ) : OrganizationBuilder
  + build() : Organization
}

OrganizationBuilder -->  LdapConfiguration
OrganizationBuilder --> Place
OrganizationBuilder ..> "<<create>>" Organization
OrganizationBuilder --|> AbsOrganizationBuilder
@enduml
