@startuml RecoveryPasswordController
!include ../../../../../../style/class.pu

class controllers.PasswordRecoveryController {
    - userRepository
    : UserRepository {frozen}
    - smtpMailSender
    : SmtpMailSenderConfiguration {frozen}
    - {static} EMAIL_BODY : String

    --

    + userPasswordRecovery(
        userData : UserData
        ) : Mono<Void>
}

repositories.UserRepository <.. controllers.PasswordRecoveryController
controllers.PasswordRecoveryController ..> model.api.UserData
controllers.PasswordRecoveryController ..> configuration.SmtpMailSenderConfiguration

@enduml
