@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC16

actor :amministratore: as A1
actor :owner: as A2

rectangle {
  together {
    usecase (AUC16.1) as "AUC16.1\nInserimento email gestore"
  }
}

:A1: -- AUC16.1
:A2: -- AUC16.1

@enduml
