@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC10

actor :owner: as A

rectangle {
  together {
    usecase (AUC10) as "AUC10\nRichiesta modifica organizzazione"
  }
  together {
    usecase (AUC5.3.4) as "AUC5.3.4\nModifica configurazione dettagli server LDAP"
    usecase (AUC5.3.3) as "AUC5.3.3\nModifica descrizione organizzazione"
    usecase (AUC5.3.2) as "AUC5.3.2\nModifica indirizzo organizzazione"
    usecase (AUC5.3.1) as "AUC5.3.1\nModifica nome organizzazione"
  }
}

:A: -- AUC10

(AUC5.3.1) .up.|> (AUC10) : <<include>>
(AUC5.3.2) .up.|> (AUC10) : <<include>>
(AUC5.3.3) .up.|> (AUC10) : <<include>>
(AUC5.3.4) .up.|> (AUC10) : <<include>>

@enduml
