@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC14

actor :owner: as A

rectangle {
  together {
    usecase (AUC14.1) as "AUC14.1\nInserimento e-mail gestore"
  }
}

:A: -- AUC14.1

@enduml
