@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC11 - Richiesta creazione organizzazione

actor :owner: as A

rectangle {
  together {
    usecase (AUC11) as "AUC11\nRichiesta creazione organizzazione"
  }
  together {
    usecase (AUC6.1.1) as "AUC6.1.1\nInserisci nome organizzazione"
    usecase (AUC6.1.2) as "AUC6.1.2\nInserisci indirizzo organizzazione"
    usecase (AUC6.1.3) as "AUC6.1.3\nInserisci descrizione organizzazione"
    usecase (AUC6.1.4) as "AUC6.1.4\nConfigurazione dettagli server LDAP"
  }
}

:A: -- AUC11

(AUC6.1.1) .up.|> (AUC11) : <<include>>
(AUC6.1.2) .up.|> (AUC11) : <<include>>
(AUC6.1.3) .up.|> (AUC11) : <<include>>
(AUC6.1.4) .up.|> (AUC11) : <<include>>

@enduml
