@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC4.8 - Gestione richiesta nuovo gestore

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC4.8.2) as "AUC4.8.2\nRifiuta richiesta\nnuovo gestore"
    usecase (AUC4.8.1) as "AUC4.8.1\nAccetta richiesta\nnuovo gestore"
  }
}

:A: -- AUC4.8.1
:A: -- AUC4.8.2

@enduml
