@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC4.6 - Gestione richiesta trasferimento di proprietà organizzazione

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC4.6.2) as "AUC4.6.2\nRifiuta richiesta trasferimento\ndi proprietà organizzazione"
    usecase (AUC4.6.1) as "AUC4.6.1\nAccetta richiesta trasferimento\ndi proprietà organizzazione"
  }
}

:A: -- AUC4.6.1
:A: -- AUC4.6.2

@enduml
