@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC4

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC4.1) as "AUC4.1\nRichiesta accettata"
    usecase (AUC4.2) as "AUC4.2\nRichiesta rifiutata"
  }
  usecase (AUC4.3) as "AUC4.3\nInvio risposta all'utente"
}

:A: -- AUC4.2
:A: -- AUC4.1

(AUC4.3) .left.|> (AUC4.1) : <<include>>
(AUC4.3) .up.|> (AUC4.2) : <<include>>

@enduml
