@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC4.4 - Gestione richiesta aggiunta luogo

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC4.4.2) as "AUC4.4.2\nRifiuta richiesta\naggiungi luogo"
    usecase (AUC4.4.1) as "AUC4.4.1\nAccetta richiesta\naggiungi luogo"
  }
}

:A: -- AUC4.4.1
:A: -- AUC4.4.2

@enduml
