@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC5.3.3.1.1) as "AUC5.3.3.1.1\nInserisci coordinate geografiche"
    usecase (AUC5.3.3.1.2) as "AUC5.3.3.1.2\nInserisci indirizzo luogo"
  }
}

:A: -- AUC5.3.3.1.1
:A: -- AUC5.3.3.1.2

@enduml
