@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC5

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC5.5) as "AUC5.5\nInvio richiesta aggiornamento\nlista organizzazioni"
    usecase (AUC5.4) as "AUC5.4\nSeleziona organizzazione"
    usecase (AUC5.3) as "AUC5.3\nModifica organizzazione"
    usecase (AUC5.2) as "AUC5.2\nEliminazione organizzazione"
    usecase (AUC5.1) as "AUC5.1\nCreazione organizzazione"
  }
}

:A: -- AUC5.1
:A: -- AUC5.2
:A: -- AUC5.3

(AUC5.4) .up.|> (AUC5.2) : <<include>>
(AUC5.4) .up.|> (AUC5.3) : <<include>>

(AUC5.5) .up.|> (AUC5.1) : <<include>>
(AUC5.5) .up.|> (AUC5.2) : <<include>>

@enduml
