@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC5.1

actor :amministratore: as A1

rectangle {
    together {
      usecase (AUC5.1.1) as "AUC5.1.1\nInserisci nome organizzazione"
      usecase (AUC5.1.2) as "AUC5.1.2\nInserisci descrizione organizzazione"
      usecase (AUC5.1.3) as "AUC5.1.3\nConfigurazione dettagli server LDAP"
    }
  }

:A1: -- AUC5.1.1
:A1: -- AUC5.1.2
:A1: -- AUC5.1.3
@enduml
