@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC5 - Creazione amministratore

actor :root: as A

rectangle {
  together {
    usecase (AUC5.1) as "AUC5.1\nInserimento credenziali\n--\nExtension points:\nvisualizzazione errore se non\nvengono rispettati i requisiti"
    usecase (AUC5.2) as "AUC5.2\nVerifica credenziali"
    usecase (AUC5.3) as "AUC5.3\nVisualizza creazione fallita"
  }
}

:A: -- AUC5.1

(AUC5.2) .up.|> (AUC5.1) : <<include>>
(AUC5.3) .up.|> (AUC5.1) : <<extends>>

@enduml
