@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC5.3.3.3

actor :amministratore: as A

rectangle {
  together {
    usecase (AUC5.3.3.3.1) as "AUC5.3.3.3.1\nModifica coordinate geografiche"
    usecase (AUC5.3.3.3.2) as "AUC5.3.3.3.2\nModifica indirizzo luogo"
  }
}

:A: -- AUC5.3.3.3.1
:A: -- AUC5.3.3.3.2

@enduml
