@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC6.1 - Creazione organizzazione

actor :root: as A1


rectangle {
  together {
    usecase (AUC6.1.4) as "AUC6.1.4\nConfigurazione dettagli server LDAP"
    usecase (AUC6.1.3) as "AUC6.1.3\nInserisci descrizione organizzazione"
    usecase (AUC6.1.2) as "AUC6.1.2\nInserisci indirizzo organizzazione"
    usecase (AUC6.1.1) as "AUC6.1.1\nInserisci nome organizzazione"
  }
}

:A1: -- AUC6.1.1
:A1: -- AUC6.1.2
:A1: -- AUC6.1.3
:A1: -- AUC6.1.4

@enduml
