@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC6

actor :root: as A

rectangle {
  together {
    usecase (AUC6.1) as "AUC6.1\nSeleziona account"
  }
}

:A: -- AUC6.1

@enduml
