@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC6 - Gestione organizzazione

actor :root: as A

rectangle {
  together {
    usecase (AUC6.5) as "AUC6.5\nInvio richiesta aggiornamento\nlista organizzazioni"
    usecase (AUC6.4) as "AUC6.4\nSeleziona organizzazione"
    usecase (AUC6.3) as "AUC6.3\nModifica organizzazione"
    usecase (AUC6.2) as "AUC6.2\nEliminazione organizzazione"
    usecase (AUC6.1) as "AUC6.1\nCreazione organizzazione"
  }
}

:A: -- AUC6.1
:A: -- AUC6.2
:A: -- AUC6.3

(AUC6.4) .up.|> (AUC6.2) : <<include>>
(AUC6.4) .up.|> (AUC6.3) : <<include>>

(AUC6.5) .up.|> (AUC6.1) : <<include>>
(AUC6.5) .up.|> (AUC6.2) : <<include>>

@enduml
