@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC6.3.4.1 - Aggiungi luogo

actor :root: as A

rectangle {
  together {
    usecase (AUC6.3.4.1.1) as "AUC6.3.4.1.1\nInserisci coordinate geografiche"
  }
}

:A: -- AUC6.3.4.1.1

@enduml
