@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC6.3 - Modifica organizzazione

actor :root: as A

rectangle {
  together {
    usecase (AUC6.3.5) as "AUC6.3.5\nModifica configurazione dettagli server LDAP"
    usecase (AUC6.3.4) as "AUC6.3.4\nGestione luoghi"
    usecase (AUC6.3.3) as "AUC6.3.3\nModifica descrizione organizzazione"
    usecase (AUC6.3.2) as "AUC6.3.2\nModifica indirizzo organizzazione"
    usecase (AUC6.3.1) as "AUC6.3.1\nModifica nome organizzazione"
  }
}

:A: -- AUC6.3.1
:A: -- AUC6.3.2
:A: -- AUC6.3.3
:A: -- AUC6.3.4
:A: -- AUC6.3.5

@enduml
