@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC6.3.4.3 - Modifica luogo

actor :root: as A

rectangle {
  together {
    usecase (AUC6.3.4.3.1) as "AUC6.3.4.3.1\nModifica coordinate geografiche"
  }
}

:A: -- AUC6.3.4.3.1

@enduml
