@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC7

actor :visualizzatore: as A

rectangle {
  together {
    usecase (AUC7) as "AUC7\nQuery sull'organizzazione"
  }
}

:A: -- AUC7

@enduml
