@startuml
!include ../../../../../commons/style/use-cases.pu
scale 3/4

title AUC8

actor :visualizzatore: as A

rectangle {
  together {
    usecase (AUC8) as "AUC8\nQuery sul dipendente"
  }
}

:A: -- AUC8

@enduml
