@startuml
!include ../../../../../commons/style/use-cases.pu

title AUC8 - Query sull'organizzazione

actor :visualizzatore: as A

rectangle {
  together {
    usecase (AUC8) as "AUC8\nQuery sull'organizzazione"
  }
}

:A: -- AUC8

@enduml
