@startuml ServerSecurityContextRepository_diagram
!include ../../../../../../style/class.pu

class org.springframework.security.web.server.context.ServerSecurityContextRepository <<interface>>{

}

@enduml
