@startuml FormPasswordComponent diagram
!include ../../../style/class.pu
class FormPasswordComponent {
  + pwdForm : FormGroup
  + hide : Boolean

  --

  + ngOnInit() : void
  + onTouched() : void
  + writeValue(val : PwdType) : void
  + registerOnChange(fn : () => void) : void
  + registerOnTouched(fn : () => void) : void
}

class PwdType <<interface>> {
  + pwd : String
}

FormPasswordComponent ..> PwdType
@enduml
