@startuml admin
!include ../../../../commons/style/use-cases.pu

title admin

actor :Amministratore: as A1.1

rectangle {
  together {
  usecase (AUC1.1) as "AUC1.1\nAutenticazione"
  usecase (AUC1.2) as "AUC1.2\nVerifica credenziali"
  usecase (AUC1.3) as "AUC1.3\nVisualizzazione credenziali errate"
  note "Condition: credenziali errate" as N1
  }

  usecase (AUC2) as "AUC2\nApprovazione owner"

  together {
    usecase (AUC3) as "AUC3\nApprovazione creazione organizzazione"
    usecase (AUC4) as "AUC4\nApprovazione modifica organizzazione"
  }

  together {
    usecase (AUC5) as "AUC5\nApprovazione aggiunta luogo"
    usecase (AUC6) as "AUC6\nApprovazione modifica luogo"
    usecase (AUC7) as "AUC7\nApprovazione trasferimento di proprietà organizzazione"
  }
}

AUC1.1 ..> AUC1.2 : <<include>>
AUC1.3 .. N1
N1 ..> AUC1.1 : <<extends>>

A1.1 - AUC1.1
A1.1 -- AUC2
A1.1 -- AUC3
A1.1 -- AUC4
A1.1 -- AUC5
A1.1 -- AUC6
A1.1 -- AUC7

@enduml

@startuml root
!include ../../../../commons/style/use-cases.pu

title root

actor :Amministratore: as A1.1
actor :Root: as A1.2

rectangle {
  usecase (AUC8) as "AUC8\nCreazione amministratore"

  together {
    usecase (AUC9) as "AUC9\nEliminazione organizzazione"
    usecase (AUC10) as "AUC10\nModifica organizzazione"
    usecase (AUC11) as "AUC11\nCreazione organizzazione"
  }

  together {
    usecase (AUC12) as "AUC12\nEliminazione luogo"
    usecase (AUC13) as "AUC13\nModifica luogo"
  }
  usecase (AUC14) as "AUC14\nEliminazione account"
}

A1.1 <|-- A1.2

A1.2 -- AUC8
A1.2 -- AUC9
A1.2 -- AUC10
A1.2 -- AUC11
A1.2 -- AUC12
A1.2 -- AUC13
A1.2 -- AUC14
@enduml

@startuml visualizzatore
!include ../../../../commons/style/use-cases.pu

title Visualizzatore

actor :Visualizzatore: as A2.1

rectangle {
  usecase (AUC17) as "AUC17\nLogin"

  together {
    usecase (AUC15) as "AUC15\nQuery sull'organizzazione"
    usecase (AUC16) as "AUC16\nQuery sul dipendente"
  }
}

A2.1 -- AUC15
A2.1 -- AUC16
A2.1 -- AUC17

@enduml

@startuml gestore
!include ../../../../commons/style/use-cases.pu

title gestore

actor :Visualizzatore: as A2.1
actor :Gestore: as A2.2

rectangle {
  together {
    usecase (AUC18) as "AUC18\nRichiesta aggiunta luogo"
    usecase (AUC19) as "AUC19\nRichiesta rimozione luogo"
    usecase (AUC20) as "AUC20\nRichiesta modifica luogo"
  }

  usecase (AUC21) as "AUC21\nRichiesta modifica parametri organizzazione"
}

A2.1 <|-- A2.2

A2.2 -- AUC18
A2.2 -- AUC19
A2.2 -- AUC20
A2.2 -- AUC21
@enduml

@startuml owner
!include ../../../../commons/style/use-cases.pu

title owner

actor :Gestore: as A2.2
actor :Owner: as A2.3

rectangle {
    together {
    usecase (AUC22) as "AUC22\nNomina visualizzatore"
    usecase (AUC23) as "AUC23\nNomina gestore"
    }

    together {
    usecase (AUC24) as "AUC24\nRichiesta creazione organizzazione"
    usecase (AUC25) as "AUC25\nRichiesta cedimento proprietà di organizzazione"
    }
}

A2.2 <|-- A2.3

:A2.3: -- AUC22
:A2.3: -- (AUC23)
:A2.3: -- (AUC24)
:A2.3: -- (AUC25)
@enduml
