@startuml autenticazione-ldap-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC3.3.1) as "UUC3.3.1\nInserimento username\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC3.3.2) as "UUC3.3.2\nInserimento password\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC3.3.3) as "UUC3.3.3\nInformazioni autenticazione non valide"
  }
}

:A: -- (UUC3.3.1)
:A: -- (UUC3.3.2)

(UUC3.3.1) <.left. (UUC3.3.3) : <<extends>>
(UUC3.3.3) .left.> (UUC3.3.2) : <<extends>>

@enduml
