@startuml autenticazione-ldap-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A
actor :server LDAP: as B

rectangle {
  together {
    usecase (UUC4.3.1) as "UUC4.3.1\nInserimento username\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC4.3.2) as "UUC4.3.2\nInserimento password\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC4.3.3) as "UUC4.3.3\nInformazioni autenticazione non valide"
  }
}

:A: -- (UUC4.3.1)
:A: -- (UUC4.3.2)
(UUC4.3.1) -- :B:
(UUC4.3.2) -- :B:

(UUC4.3.1) <.left. (UUC4.3.3) : <<extends>>
(UUC4.3.3) .left.> (UUC4.3.2) : <<extends>>


@enduml
