@startuml autenticazione-ldap-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC3.2.1) as "UUC3.2.1\nInserimento username\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC3.2.2) as "UUC3.2.2\nInserimento password\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC3.2.3) as "UUC3.2.3\nInformazioni autenticazione non valide"
  }
}

:A: -- (UUC3.2.1)
:A: -- (UUC3.2.2)

(UUC3.2.1) <.left. (UUC3.2.3) : <<extends>>
(UUC3.2.3) .left.> (UUC3.2.2) : <<extends>>

@enduml
