@startuml collegamento-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A3
actor :server LDAP: as A4

rectangle {
  together {
    usecase (UUC8) as "UUC8\nCollegamento organizzazione\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC9) as "UUC9\nCollegamento organizzazione pubblica"
    usecase (UUC10) as "UUC10\nCollegamento organizzazione privata"
    usecase (UUC17) as "UUC17\nVisualizzazione errore\nrete mancante"
  }
}

:A3: -- (UUC8)
(UUC8) <.left. (UUC17) : <<extends>>
(UUC8) <|-- (UUC9)
(UUC8) <|-- (UUC10)
(UUC10) -- :A4:

@enduml


@startuml autenticazione-ldap-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC10.1) as "UUC10.1\nInserimento username\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC10.2) as "UUC10.2\nInserimento password\norganizzazione\n--\nExtension points:\nVisualizzazione errore\ncredenziali errate"
    usecase (UUC10.3) as "UUC10.3\nVisualizzazione errore autenticazione LDAP"
  }
}

:A: -- (UUC10.1)
:A: -- (UUC10.2)

(UUC10.1) <.left. (UUC10.3) : <<extends>>
(UUC10.3) .left.> (UUC10.2) : <<extends>>

@enduml
