@startuml collegamento-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A3

rectangle {
  together {
    usecase (UUC4) as "UUC4\nGestione lista organizzazioni"
    usecase (UUC5.1) as "UUC5.1\nFiltra organizzazioni\nnon collegate"
  }
}

:A3: -- (UUC4)

(UUC5.1) <.up. (UUC4) : <<include>>

@enduml
