@startuml disconnessione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A3

rectangle {
  together {
    usecase (UUC15) as "UUC15\nDisconnessione utente\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC17) as "UUC17\nVisualizzazione errore\nrete mancante"
  }
}

:A3: -- (UUC15)

(UUC17) .up.> (UUC15) : <<extends>>

@enduml
