@startuml disconnessione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A3

rectangle {
  together {
    usecase (UUC16) as "UUC16\nDisconnessione utente\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC18) as "UUC18\nVisualizzazione errore\nrete mancante"
  }
}

:A3: -- (UUC16)

(UUC18) .up.> (UUC16) : <<extends>>

@enduml
