@startuml disconnessione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A3

rectangle {
  together {
    usecase (UUC9) as "UUC9\nDisconnessione utente\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC11) as "UUC11\nVisualizzazione errore\nrete mancante"
  }
}

:A3: -- (UUC9)

(UUC11) .up.> (UUC9) : <<extends>>

@enduml
