@startuml eliminazione-account
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC17.1) as "UUC17.1\nConferma eliminazione account\n--\nExtension points:\nVisualizzazione errore in\ncaso di eliminazione account\nin mancanza di rete"
    usecase (UUC18) as "UUC18\nVisualizzazione errore\nrete mancante"
  }
}

:A: -- (UUC17.1)

(UUC18) .up.> (UUC17.1) : <<extends>>

@enduml
