@startuml eliminazione-account
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC10.1) as "UUC10.1\nConferma eliminazione account\n--\nExtension points:\nVisualizzazione errore in\ncaso di eliminazione account\nin mancanza di rete"
    usecase (UUC11) as "UUC11\nVisualizzazione errore\nrete mancante"
  }
}

:A: -- (UUC10.1)

(UUC11) .up.> (UUC10.1) : <<extends>>

@enduml
