@startuml eliminazione-account
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC16.1) as "UUC16.1\nConferma eliminazione account\n--\nExtension points:\nVisualizzazione errore in\ncaso di eliminazione account\nin mancanza di rete"
    usecase (UUC17) as "UUC17\nVisualizzazione errore\nrete mancante"
  }
}

:A: -- (UUC16.1)

(UUC17) .up.> (UUC16.1) : <<extends>>

@enduml
