@startuml gestione-lista-organizzazioni
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A
actor :server LDAP: as B

rectangle {
  together {
    usecase (UUC3.1) as "UUC3.1\nAggiornamento\nlista organizzazioni\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC3.2) as "UUC3.2\nSeleziona organizzazioni\n--\nExtension points:\n-Visualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC11) as "UUC11\nVisualizzazione errore\nrete mancante"
  }

}

:A: -- (UUC3.1)
:A: -- (UUC3.2)
(UUC3.2) -- :B:

(UUC3.1) <.left. (UUC11) : <<extends>>
(UUC11) .left.> (UUC3.2) : <<extends>>

@enduml
