@startuml gestione-lista-organizzazioni
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC4) as "UUC4\nVisualizza\nlista organizzazioni\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC5) as "UUC5\nVisualizza\nlista organizzazioni collegate"
    usecase (UUC6) as "UUC6\nVisualizza\nlista organizzazioni non collegate"
    usecase (UUC18) as "UUC18\nVisualizzazione errore\nrete mancante"
  }

}

:A: -- (UUC4)
(UUC4) <|-- (UUC5)
(UUC4) <|-- (UUC6)

(UUC4) <.left. (UUC18) : <<extends>>


@enduml


@startuml visualizza-organizzazione-collegata
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC5.1) as "UUC5.1\nVisualizza\norganizzazione in lista collegata"
  }
}

:A: -- (UUC5.1)

@enduml


@startuml visualizza-organizzazione-non-collegata
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC6.1) as "UUC6.1\nVisualizza\norganizzazione in lista non collegata"
  }
}

:A: -- (UUC6.1)

@enduml
@startuml visualizza-info-organizzazione-collegata
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC5.1.1) as "UUC5.1.1\nVisualizza\nnome organizzazione collegata"
    usecase (UUC5.1.2) as "UUC5.1.2\nVisualizza\ndescrizione organizzazione collegata"
    usecase (UUC5.1.3) as "UUC5.1.3\nVisualizza\nstato organizzazione collegata"
  }
}

:A: -- (UUC5.1.1)
:A: -- (UUC5.1.2)
:A: -- (UUC5.1.3)

@enduml


@startuml visualizza-info-organizzazione-non-collegata
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A


rectangle {
  together {
    usecase (UUC6.1.1) as "UUC6.1.1\nVisualizza\nnome organizzazione non collegata"
    usecase (UUC6.1.2) as "UUC6.1.2\nVisualizza\ndescrizione organizzazione non collegata"
    usecase (UUC6.1.3) as "UUC6.1.3\nVisualizza\nstato organizzazione non collegata"
  }
}

:A: -- (UUC6.1.1)
:A: -- (UUC6.1.2)
:A: -- (UUC6.1.3)

@enduml
