@startuml gestione-lista-organizzazioni
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC4) as "UUC4\nVisualizza\nlista organizzazioni\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"
    usecase (UUC5) as "UUC5\nVisualizza\nlista organizzazioni collegate"
    usecase (UUC6) as "UUC6\nVisualizza\nlista organizzazioni non collegate"
    usecase (UUC17) as "UUC17\nVisualizzazione errore\nrete mancante"
  }

}

:A: -- (UUC4)
(UUC4) <|-- (UUC5)
(UUC4) <|-- (UUC6)

(UUC4) <.left. (UUC17) : <<extends>>


@enduml


@startuml visualizza-organizzazione-collegata
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC5.1) as "UUC5.1\nVisualizza\norganizzazione in lista collegata"
  }
}

:A: -- (UUC5.1)

@enduml


@startuml visualizza-organizzazione-non-collegata
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC6.1) as "UUC6.1\nVisualizza\norganizzazione in lista non collegata"
  }
}

:A: -- (UUC6.1)

@enduml
