
@startuml scelta-noto-o-incognito
!include ../../../../../../commons/style/use-cases.pu

actor :utente collegato: as A3

actor :utente noto: as A3.1
actor :utente incognito: as A3.2

:A3.1: -up-|> :A3:
:A3.2: -up-|> :A3:

rectangle {
  together {
    usecase (UUC12.1) as "UUC12.1\nPassaggio a incognito"
    usecase (UUC12.2) as "UUC12.2\nPassaggio a noto"
  }
}

:A3.1: -- (UUC12.1)
:A3.2: -- (UUC12.2)

@enduml
