
@startuml passaggio-noto
!include ../../../../../../commons/style/use-cases.pu

actor :utente incognito: as A3

rectangle {
  together {
    usecase (UUC18) as "UUC18\nVisualizzazione errore\nrete mancante"
    usecase (UUC12) as "UUC12\nPassaggio a noto\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"

  }
}

:A3: -- (UUC12)

(UUC12) <- (UUC18) : <<extends>>
@enduml



@startuml passaggio-incognito
!include ../../../../../../commons/style/use-cases.pu

actor :utente noto: as A3

rectangle {
  together {
    usecase (UUC18) as "UUC18\nVisualizzazione errore\nrete mancante"
    usecase (UUC13) as "UUC13\nPassaggio a incognito\n--\nExtension points:\nVisualizzazione errore in\ncaso di disconnessione\nin mancanza di rete"

  }
}

:A3: -- (UUC13)

(UUC13) <- (UUC18) : <<extends>>
@enduml


