@startuml recupero-credenziali
!include ../../../../../../commons/style/use-cases.pu

actor :utente non autenticato: as A

rectangle {
  together {
    usecase (UUC3) as "UUC3\nRecupero password"
  }
}

:A: -- (UUC3)

@enduml

@startuml recupero-password
!include ../../../../../../commons/style/use-cases.pu

actor :utente non autenticato: as A

rectangle {
  together {
    usecase (UUC3.1) as "UUC3.1\nInserimento\nemail di registrazione\n--\nExtension points:\nVisualizzazione errore se l'email\nnon è registrata"
    usecase (UUC3.2) as "UUC3.2\nReimpostazione password"
    usecase (UUC3.3) as "UUC3.3\nMail recupero credenziali\nnon valida"
  }
}

:A: -- (UUC3.1)
:A: -- (UUC3.2)

(UUC3.3) .up.> (UUC3.1) : <<extends>>

@enduml

@startuml reimpostazione-password
!include ../../../../../../commons/style/use-cases.pu

actor :utente non autenticato: as A

rectangle {
  together {
    usecase (UUC3.2.1) as "UUC3.2.1\nInserimento nuova password\n--\nExtension points:\nVisualizzazione errore se la\npassword non rispetta i criteri"
    usecase (UUC3.2.2) as "UUC3.2.2\nInserimento conferma password\n--\nExtension points:\nVisualizzazione errore se le\ndue password non coincidono"
    usecase (UUC3.2.3) as "UUC3.2.3\nPassword recupero credenziali\nnon valida"
    usecase (UUC3.2.4) as "UUC3.2.4\nConferma password recupero credenziali\nnon valida"
  }
}

:A: -- (UUC3.2.1)
:A: -- (UUC3.2.2)

(UUC3.2.4) .up.> (UUC3.2.2) : <<extends>>
(UUC3.2.3) .up.> (UUC3.2.1) : <<extends>>

@enduml
