@startuml scollegamento-organizzazione
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A3

rectangle {
  together {
    usecase (UUC4) as "UUC4\nGestione lista organizzazioni\n--\nExtension points:\nVisualizzazione errore in caso di\nselezionamento di un'organizzazione\n con rete mancante"
    usecase (UUC6.1) as "UUC6.1\nFiltra organizzazioni \ncollegate"
    usecase (UUC12) as "UUC.nd\nVisualizzazione errore\nrete mancante"
  }
}

:A3: -- (UUC4)

(UUC6.1) <.up. (UUC4) : <<include>>
(UUC12) .up.> (UUC4) : <<extends>>

@enduml
