@startuml storico-utente
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC7) as "UUC7\nVisualizzazione storico accessi\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta storico\nin mancanza di rete"
    usecase (UUC11) as "UUC11\nVisualizzazione errore\nrete mancante"
    note right of (UUC7): implementazione opzionale
  }
}

:A: -- (UUC7)

(UUC11) .up.> (UUC7) : <<extends>>

@enduml
