@startuml storico-utente
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC14) as "UUC14\nVisualizzazione storico accessi\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta storico\nin mancanza di rete"
    usecase (UUC18) as "UUC18\nVisualizzazione errore\nrete mancante"
    note right of (UUC14): implementazione opzionale
  }
}

:A: -- (UUC14)

(UUC18) .up.> (UUC14) : <<extends>>

@enduml
