@startuml storico-utente
!include ../../../../../../commons/style/use-cases.pu

actor :utente autenticato: as A

rectangle {
  together {
    usecase (UUC13) as "UUC13\nVisualizzazione storico accessi\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta storico\nin mancanza di rete"
    usecase (UUC17) as "UUC17\nVisualizzazione errore\nrete mancante"
    note right of (UUC13): implementazione opzionale
  }
}

:A: -- (UUC13)

(UUC17) .up.> (UUC13) : <<extends>>

@enduml
