@startuml visualizzazione-tempo-trascorso-nell-organizzazione-corrente
!include ../../../../../../commons/style/use-cases.pu

actor :utente collegato: as A3

rectangle {
  together {
    usecase (UUC14) as "UUC14\nVisualizzazione tempo \nnell'organizzazione corrente\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta tempo trascorso\nin mancanza di rete"
    usecase (UUC17) as "UUC17\nVisualizzazione errore\nrete mancante"
    note right of (UUC14): implementazione opzionale
  }
}

:A3: -- (UUC14)

(UUC17) .up.> (UUC14) : <<extends>>

@enduml
