@startuml visualizzazione-tempo-trascorso-nell-organizzazione-corrente
!include ../../../../../../commons/style/use-cases.pu

actor :utente collegato: as A3

rectangle {
  together {
    usecase (UUC15) as "UUC15\nVisualizzazione tempo \nnell'organizzazione corrente\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta tempo trascorso\nin mancanza di rete"
    usecase (UUC18) as "UUC18\nVisualizzazione errore\nrete mancante"
    note right of (UUC15): implementazione opzionale
  }
}

:A3: -- (UUC15)

(UUC18) .up.> (UUC15) : <<extends>>

@enduml
