@startuml visualizzazione-tempo-trascorso-nell-organizzazione-corrente
!include ../../../../../../commons/style/use-cases.pu

actor :utente collegato: as A3

rectangle {
  together {
    usecase (UUC9) as "UUC9\nVisualizzazione tempo \nnell'organizzazione corrente\n--\nExtension points:\nVisualizzazione errore in\ncaso di richiesta tempo trascorso\nin mancanza di rete"
    usecase (UUC12) as "UUC12\nVisualizzazione errore\nrete mancante"
    note right of (UUC9): implementazione opzionale
  }
}

:A3: -- (UUC9)

(UUC12) .up.> (UUC9) : <<extends>>

@enduml
